### ISSUE TITLE
readme: describe the tool

### ISSUE THREAD

**Issue by TomasTomecek** [webknjaz/ansiwatch-bot#1]
I read the readme and I have no idea what this tool does and why I should use it. I suggest adding such info.

**Comment by webknjaz** [comment]
Well.. Yeah, it's more like my playground at the moment. But I hear you :) I'll try to come up with something.
Long story short is that it runs ansible-review and posts results via Checks API like this https://github.com/webknjaz/ansible-gentoo-laptop/pull/4/checks?check_run_id=26277133

Oh, and it also creatively uses CherryPy features allowing to abstract web server parts away from the actual logic needed for the integration :)
